// Bilingual copy. English first, with Japanese variants for hero, privacy and CTA
// as specified in the brief. The brand name "Gamu Baby" is never translated.

const COPY = {
  en: {
    nav: { features: "Features", privacy: "Privacy", pro: "Pro", get: "Get Gamu Baby" },
    hero: {
      eyebrow: "Offline-first baby tracker",
      h1: "Private baby tracking for everyday care and tiny milestones.",
      sub: "Log feeding, diapers, sleep, growth, photos, and memories without an account or cloud sync.",
      primary: "Download on Google Play",
      secondary: "See how it works",
      trust: ["Offline-first", "No account", "No ads", "One-time Pro"],
    },
    first: {
      eyebrow: "Useful in under a minute",
      h2: "Open the app. Tap once. Done.",
      sub: "No onboarding maze, no email, no setup wizard. Gamu Baby is built for tired hands at 3 a.m.",
      steps: [
        { t: "Create a baby profile", d: "Name, birthday, optional photo. Add as many babies as your family needs.", time: "~20 sec" },
        { t: "Log your first care event", d: "A feed, a diaper, a nap. One tap on the home screen and it's recorded.", time: "~5 sec" },
        { t: "See today's timeline", d: "Everything you've logged, in order, ready to share with a partner or pediatrician.", time: "Instant" },
      ],
      cta: "Useful in under a minute. Forever, after that.",
    },
    feat: {
      eyebrow: "Feature proof",
      h2: "A calm record of the things that actually happen.",
      sub: "Built around five screens you'll open every day — and a few that you'll cherish years from now.",
      cards: [
        { tag: "Milestones · Memories", t: "Track every milestone, automatically organized.", d: "142 developmental moments from birth to 60 months. Tap when it happens, attach a photo, write a sentence. The app remembers what's next.", pills: ["142 milestones", "Birth → 60 months", "Photo attachments"], img: "assets/01-milestones.png" },
        { tag: "Age-based checklists", t: "Never miss a stage.", d: "Movement, vision and hearing, social, language — broken down by age band. Add custom milestones for the ones only your family knows.", pills: ["Age 0–60m", "Custom too"], img: "assets/02-checklist.png" },
        { tag: "Quick diary logs", t: "One tap. Logged.", d: "Sleep, bottle, breastfeed, pee, poo, awake time, growth, health notes. Flag anything you want to remember for the doctor.", pills: ["Quick log", "Doctor flags", "Awake timer"], img: "assets/03-diary.png" },
        { tag: "Journey timeline", t: "A timeline they'll love rereading.", d: "Photos, notes, and milestones woven together into a visual story you'll revisit forever. Auto-grouped by month and stage.", pills: ["Photo memories", "Auto-grouped"], img: "assets/04-journey.png" },
        { tag: "Shareable milestone cards", t: "Beautiful one-tap progress cards.", d: "Send a single image with the latest milestone, growth and a sweet portrait. Perfect for family group chats.", pills: ["One tap", "Image export"], img: "assets/05-share.png" },
        { tag: "Pediatrician PDF", t: "Hand the doctor a clean summary.", d: "Export flagged logs, growth and recent milestones to a one-page PDF before your next visit. No data leaves your phone unless you share it.", pills: ["PDF export", "Doctor-friendly"] },
        { tag: "Year in Review PDF", t: "A keepsake at the end of every year.", d: "A printable summary of milestones, photos and growth from the past 12 months. Save it, print it, mail it to grandparents.", pills: ["Yearly PDF", "Printable"] },
        { tag: "Private backup & restore", t: "Your data, in your hands.", d: "Export a backup file whenever you like. Restore on a new phone with a single tap. No account required, ever.", pills: ["Local backup", "One-tap restore"] },
      ],
    },
    privacy: {
      eyebrow: "Privacy by design",
      h2: "Your baby's data stays yours.",
      sub: "No accounts to forget. No syncing in the background. No ad networks watching your child grow. Gamu Baby was built around a single rule: nothing leaves the phone unless you send it.",
      items: [
        { t: "Stored on your device", d: "Logs, photos and notes live in local storage on your phone — nowhere else." },
        { t: "No account required", d: "No email, no password, no sign-up. Open the app and start." },
        { t: "No ads. No selling baby data.", d: "We have no ad SDKs and no analytics that read your child's information." },
        { t: "You control every export", d: "Backups, PDFs and share cards only leave your device when you choose to send them." },
      ],
      card: {
        badge: "Local-only",
        h: "Your phone is the server.",
        d: "Gamu Baby works fully offline. Flights, basements, formula-haze nights at 3 a.m. — it just keeps working.",
        meta: [
          { k: "Accounts", v: "0" },
          { k: "Trackers", v: "0" },
          { k: "Ad SDKs", v: "0" },
          { k: "Cloud sync", v: "Off by default" },
        ],
        never: ["We never read your logs.", "We never sell baby data.", "We never require a login."],
      },
    },
    care: {
      eyebrow: "Caregiver invite",
      h2: "Share the app with the people who help.",
      sub: "Partners, grandparents, babysitters. Send a code and they can install Gamu Baby and start their own calm record on their phone — no group account, no shared cloud.",
      qrTitle: "Invite a caregiver",
      qrSub: "Scan to install. Each phone keeps its own private record.",
      qrBtnPrimary: "Share invite",
      qrBtnSecondary: "Copy code",
      disclaim: "An invite helps another caregiver install the app. It does not automatically expose your private logs — sharing is always something you choose, log by log.",
    },
    pro: {
      eyebrow: "Gamu Baby Pro",
      h2: "One quiet purchase. The whole tracker, forever.",
      sub: "Pro keeps Gamu Baby ad-free, account-free and made by humans. It's a one-time purchase — never a subscription.",
      price: "¥1,800",
      once: "One-time · No subscription",
      feat: [
        "Advanced diary logs (growth, health flags, awake timer)",
        "Multiple baby profiles for twins and siblings",
        "Shareable milestone cards",
        "Pediatrician PDF export",
        "Year in Review PDF keepsake",
        "Backup & restore",
      ],
      note: "Free version covers daily logs and basic milestones — try the app first, upgrade only if it earns its keep.",
      cta: "Get it on Google Play",
    },
    final: {
      h2: "Start privately. Today.",
      sub: "Open the app and you're already tracking. No account needed.",
      primary: "Download on Google Play",
      reass: "Free to install · One-time Pro available in-app",
    },
    foot: {
      tag: "Made for parents, by parents.",
      moreLabel: "More apps from this developer →",
      moreHref: "https://play.google.com/store/apps/dev?id=8831894198403002159",
      links: [],
      copy: "© 2026 Gamu Baby",
    },
  },

  ja: {
    nav: { features: "機能", privacy: "プライバシー", pro: "Pro", get: "Gamu Baby を入手" },
    hero: {
      eyebrow: "オフラインファーストの育児記録",
      h1: "毎日のお世話と、小さな成長のための、静かな育児記録。",
      sub: "授乳・おむつ・睡眠・成長・写真・思い出。アカウント登録もクラウド同期も必要ありません。",
      primary: "Google Play で入手",
      secondary: "どう動くかを見る",
      trust: ["オフライン対応", "アカウント不要", "広告なし", "買い切り Pro"],
    },
    first: {
      eyebrow: "1分以内で使えます",
      h2: "アプリを開く。タップ。記録完了。",
      sub: "面倒な初期設定もメール登録もなし。深夜3時の眠い手のために作りました。",
      steps: [
        { t: "赤ちゃんのプロフィールを作成", d: "名前、誕生日、写真は任意。何人でも追加できます。", time: "約20秒" },
        { t: "最初のお世話を記録", d: "授乳、おむつ、お昼寝。ホーム画面でワンタップ。", time: "約5秒" },
        { t: "今日のタイムラインを確認", d: "記録したすべてを、パートナーや小児科の先生と共有できる形で。", time: "すぐに" },
      ],
      cta: "1分以内で使える。そしてその後もずっと。",
    },
    feat: {
      eyebrow: "機能",
      h2: "本当に起こることを、静かに記録する。",
      sub: "毎日開きたくなる5つの画面と、何年か先に大切に見返すいくつかの画面。",
      cards: [
        { tag: "マイルストーン・思い出", t: "すべての成長を、自動で整理。", d: "誕生から60ヶ月までの142の発達マイルストーン。タップして写真と一文を添えるだけ。", pills: ["142件", "0–60ヶ月", "写真添付"], img: "assets/01-milestones.png" },
        { tag: "年齢別チェックリスト", t: "発達段階を見逃さない。", d: "運動、視覚・聴覚、社会性、言語。月齢別に整理。家族だけの項目も追加できます。", pills: ["0〜60ヶ月", "カスタム可"], img: "assets/02-checklist.png" },
        { tag: "ワンタップ日記", t: "ワンタップで、記録完了。", d: "睡眠、ミルク、母乳、おしっこ、うんち、覚醒時間、成長、健康メモ。気になることに先生用フラグも。", pills: ["クイック記録", "受診用フラグ", "覚醒タイマー"], img: "assets/03-diary.png" },
        { tag: "ジャーニー", t: "何度も読み返したくなるタイムライン。", d: "写真、メモ、マイルストーンを織り合わせた成長のストーリー。月ごとに自動でまとめます。", pills: ["写真メモリ", "自動整理"], img: "assets/04-journey.png" },
        { tag: "共有カード", t: "美しい成長カードを、ワンタップで。", d: "最新のマイルストーン、成長、可愛いポートレートを一枚に。家族のグループチャットにぴったり。", pills: ["ワンタップ", "画像で書き出し"], img: "assets/05-share.png" },
        { tag: "受診用PDF", t: "先生に渡せるきれいなサマリー。", d: "フラグした記録、成長、最近のマイルストーンを1ページにまとめてPDF出力。", pills: ["PDF出力", "受診用"] },
        { tag: "年間レビューPDF", t: "1年の終わりに、思い出を一冊に。", d: "この1年のマイルストーン、写真、成長を印刷できるPDFに。祖父母に郵送するのも素敵。", pills: ["年間PDF", "印刷可"] },
        { tag: "バックアップと復元", t: "データはあなたの手の中に。", d: "バックアップファイルをいつでも書き出し、新しい端末にワンタップで復元。アカウント不要。", pills: ["ローカル保存", "ワンタップ復元"] },
      ],
    },
    privacy: {
      eyebrow: "設計からプライベート",
      h2: "赤ちゃんのデータは、あなたのもの。",
      sub: "忘れるアカウントも、裏で動く同期も、子どもの成長を見つめる広告ネットワークもありません。Gamu Baby は一つのルールのもとに作られています — あなたが送らない限り、何も端末から出ません。",
      items: [
        { t: "端末に保存", d: "記録、写真、メモはすべて端末のローカルストレージに保存されます。" },
        { t: "アカウント不要", d: "メールもパスワードもサインアップも不要。開いたらすぐに使えます。" },
        { t: "広告なし。データ販売なし。", d: "広告SDKも、子どもの情報を読む解析ツールも入っていません。" },
        { t: "書き出しはあなたの意思で", d: "バックアップ、PDF、共有カードは、あなたが送ると決めたときだけ端末を離れます。" },
      ],
      card: {
        badge: "ローカル専用",
        h: "あなたの端末がサーバー。",
        d: "完全にオフラインで動きます。飛行機の中でも、地下でも、深夜3時の眠い時間でも、ちゃんと動きます。",
        meta: [
          { k: "アカウント", v: "0" },
          { k: "トラッカー", v: "0" },
          { k: "広告SDK", v: "0" },
          { k: "クラウド同期", v: "初期設定でオフ" },
        ],
        never: ["記録を読みません。", "データを販売しません。", "ログインを求めません。"],
      },
    },
    care: {
      eyebrow: "家族を招待",
      h2: "お世話する人と、アプリを共有。",
      sub: "パートナー、祖父母、ベビーシッター。コードを送れば、それぞれの端末で Gamu Baby を始められます — グループアカウントも共有クラウドもありません。",
      qrTitle: "家族を招待する",
      qrSub: "スキャンしてインストール。それぞれの端末で自分の記録を。",
      qrBtnPrimary: "招待を送る",
      qrBtnSecondary: "コードをコピー",
      disclaim: "招待は、相手がアプリをインストールするのを助けるだけです。あなたの記録が自動的に共有されることはありません — 共有は常に、記録ごとに、あなたが選びます。",
    },
    pro: {
      eyebrow: "Gamu Baby Pro",
      h2: "一度だけの購入で、すべての機能を、ずっと。",
      sub: "Pro があるおかげで、Gamu Baby は広告なし、アカウントなしで、人の手で作り続けられます。サブスクリプションではなく、買い切りです。",
      price: "¥1,800",
      once: "買い切り・サブスクなし",
      feat: [
        "高度な日記項目(成長・受診フラグ・覚醒タイマー)",
        "双子・きょうだいのための複数プロフィール",
        "共有カード",
        "受診用PDFエクスポート",
        "年間レビューPDF",
        "バックアップ & 復元",
      ],
      note: "無料版でも日々の記録と基本のマイルストーンは使えます。まずは試して、気に入ったら Pro へ。",
      cta: "Google Play で入手",
    },
    final: {
      h2: "静かに、今日から。",
      sub: "アプリを開いた瞬間から、もう記録が始まっています。アカウントは要りません。",
      primary: "Google Play で入手",
      reass: "インストール無料・Pro はアプリ内で買い切り",
    },
    foot: {
      tag: "親が、親のために作りました。",
      moreLabel: "このデベロッパーの他のアプリ →",
      moreHref: "https://play.google.com/store/apps/dev?id=8831894198403002159",
      links: [],
      copy: "© 2026 Gamu Baby",
    },
  },

  pt: {
    nav: { features: "Recursos", privacy: "Privacidade", pro: "Pro", get: "Obter Gamu Baby" },
    hero: {
      eyebrow: "Rastreador de bebé offline",
      h1: "Registo privado do dia a dia e dos pequenos marcos do seu bebé.",
      sub: "Registe amamentação, fraldas, sono, crescimento, fotografias e memórias sem conta nem sincronização na nuvem.",
      primary: "Descarregar no Google Play",
      secondary: "Ver como funciona",
      trust: ["Funciona offline", "Sem conta", "Sem anúncios", "Pro pago uma só vez"],
    },
    first: {
      eyebrow: "Útil em menos de um minuto",
      h2: "Abrir a app. Um toque. Pronto.",
      sub: "Sem labirinto de onboarding, sem email, sem assistente de configuração. Gamu Baby foi feito para mãos cansadas às 3 da manhã.",
      steps: [
        { t: "Crie um perfil do bebé", d: "Nome, data de nascimento, foto opcional. Adicione quantos bebés a sua família precisar.", time: "~20 seg" },
        { t: "Registe o primeiro evento", d: "Uma mamada, uma fralda, uma sesta. Um toque no ecrã inicial e fica gravado.", time: "~5 seg" },
        { t: "Veja a linha do dia", d: "Tudo o que registou, por ordem, pronto a partilhar com o parceiro ou o pediatra.", time: "Instantâneo" },
      ],
      cta: "Útil em menos de um minuto. E para sempre, depois disso.",
    },
    feat: {
      eyebrow: "Provas em forma de recursos",
      h2: "Um registo calmo das coisas que realmente acontecem.",
      sub: "Construído à volta de cinco ecrãs que vai abrir todos os dias — e alguns que vai querer guardar para sempre.",
      cards: [
        { tag: "Marcos · Memórias", t: "Acompanhe cada marco, organizado automaticamente.", d: "142 momentos de desenvolvimento, do nascimento aos 60 meses. Toque quando acontece, anexe uma foto, escreva uma frase. A app lembra-se do que vem a seguir.", pills: ["142 marcos", "0 → 60 meses", "Anexar fotos"], img: "assets/01-milestones.png" },
        { tag: "Checklists por idade", t: "Não perca nenhuma fase.", d: "Movimento, visão e audição, social, linguagem — divididos por faixa etária. Adicione marcos personalizados para os que só a sua família conhece.", pills: ["0–60 meses", "Personalizável"], img: "assets/02-checklist.png" },
        { tag: "Diário rápido", t: "Um toque. Registado.", d: "Sono, biberão, mamada, xixi, cocó, tempo acordado, crescimento, notas de saúde. Marque tudo o que queira lembrar para o médico.", pills: ["Registo rápido", "Marcas para o médico", "Temporizador"], img: "assets/03-diary.png" },
        { tag: "Linha do tempo", t: "Uma linha do tempo para reler vezes sem conta.", d: "Fotos, notas e marcos tecidos numa história visual que vai querer revisitar. Agrupado por mês e fase, automaticamente.", pills: ["Memórias com fotos", "Agrupado automaticamente"], img: "assets/04-journey.png" },
        { tag: "Cartões partilháveis", t: "Lindos cartões de progresso, com um toque.", d: "Envie uma imagem com o marco mais recente, crescimento e um retrato fofo. Perfeito para os grupos da família.", pills: ["Um toque", "Exportar imagem"], img: "assets/05-share.png" },
        { tag: "PDF para o pediatra", t: "Entregue ao médico um resumo limpo.", d: "Exporte registos marcados, crescimento e marcos recentes num PDF de uma página antes da próxima consulta. Nada sai do seu telefone sem si.", pills: ["Exportar PDF", "Pensado para médicos"] },
        { tag: "PDF Resumo Anual", t: "Uma recordação no fim de cada ano.", d: "Um resumo imprimível dos marcos, fotos e crescimento dos últimos 12 meses. Guarde, imprima, envie aos avós.", pills: ["PDF anual", "Imprimível"] },
        { tag: "Cópia & restauro", t: "Os seus dados, nas suas mãos.", d: "Exporte um ficheiro de cópia de segurança quando quiser. Restaure num telefone novo com um toque. Sem conta, nunca.", pills: ["Backup local", "Restauro num toque"] },
      ],
    },
    privacy: {
      eyebrow: "Privacidade por design",
      h2: "Os dados do seu bebé continuam seus.",
      sub: "Sem contas para esquecer. Sem sincronização em segundo plano. Sem redes de publicidade a ver o seu filho crescer. Gamu Baby foi feito com uma única regra: nada sai do telefone a não ser que o envie.",
      items: [
        { t: "Guardado no seu dispositivo", d: "Registos, fotos e notas ficam no armazenamento local do telefone — em mais lado nenhum." },
        { t: "Sem necessidade de conta", d: "Sem email, sem palavra-passe, sem registo. Abra a app e comece." },
        { t: "Sem anúncios. Sem venda de dados.", d: "Não temos SDKs de publicidade nem analíticas que leiam informação da sua criança." },
        { t: "Você decide cada exportação", d: "Cópias, PDFs e cartões só saem do dispositivo quando escolhe enviá-los." },
      ],
      card: {
        badge: "Apenas local",
        h: "O seu telefone é o servidor.",
        d: "Gamu Baby funciona totalmente offline. Voos, caves, noites confusas às 3 da manhã — continua a funcionar.",
        meta: [
          { k: "Contas", v: "0" },
          { k: "Rastreadores", v: "0" },
          { k: "SDKs de anúncios", v: "0" },
          { k: "Sync na nuvem", v: "Desligado por defeito" },
        ],
        never: ["Nunca lemos os seus registos.", "Nunca vendemos dados de bebés.", "Nunca exigimos login."],
      },
    },
    care: {
      eyebrow: "Convite a cuidador",
      h2: "Partilhe a app com quem ajuda.",
      sub: "Parceiros, avós, baby-sitters. Envie um código e instalam o Gamu Baby para começar o seu próprio registo — sem conta partilhada, sem nuvem comum.",
      qrTitle: "Convidar um cuidador",
      qrSub: "Faça scan para instalar. Cada telefone mantém o seu registo privado.",
      qrBtnPrimary: "Partilhar convite",
      qrBtnSecondary: "Copiar código",
      disclaim: "Um convite ajuda outra pessoa a instalar a app. Não expõe os seus registos automaticamente — partilhar é sempre uma escolha sua, registo a registo.",
    },
    pro: {
      eyebrow: "Gamu Baby Pro",
      h2: "Uma compra única. A app inteira, para sempre.",
      sub: "Pro mantém o Gamu Baby sem anúncios, sem contas e feito por humanos. É uma compra única — nunca uma subscrição.",
      price: "",
      once: "",
      feat: [
        "Registos de diário avançados (crescimento, marcações de saúde, temporizador)",
        "Vários perfis de bebé para gémeos e irmãos",
        "Cartões de marco partilháveis",
        "Exportação PDF para o pediatra",
        "PDF de Resumo Anual",
        "Cópia & restauro",
      ],
      note: "A versão gratuita cobre os registos diários e os marcos básicos — experimente primeiro, faça upgrade só se valer a pena.",
      cta: "Obter no Google Play",
    },
    final: {
      h2: "Comece privadamente. Hoje.",
      sub: "Abra a app e já está a registar. Não precisa de conta.",
      primary: "Descarregar no Google Play",
      reass: "Instalação grátis · Pro disponível na app",
    },
    foot: {
      tag: "Feito por pais, para pais.",
      moreLabel: "Mais apps deste developer →",
      moreHref: "https://play.google.com/store/apps/dev?id=8831894198403002159",
      links: [],
      copy: "© 2026 Gamu Baby",
    },
  },

  es: {
    nav: { features: "Funciones", privacy: "Privacidad", pro: "Pro", get: "Conseguir Gamu Baby" },
    hero: {
      eyebrow: "Seguimiento de bebé sin conexión",
      h1: "Registro privado del día a día y los pequeños hitos de tu bebé.",
      sub: "Registra tomas, pañales, sueño, crecimiento, fotos y recuerdos sin cuenta ni sincronización en la nube.",
      primary: "Descargar en Google Play",
      secondary: "Ver cómo funciona",
      trust: ["Funciona sin conexión", "Sin cuenta", "Sin anuncios", "Pro de pago único"],
    },
    first: {
      eyebrow: "Útil en menos de un minuto",
      h2: "Abre la app. Un toque. Listo.",
      sub: "Sin laberintos de bienvenida, sin email, sin asistente de configuración. Gamu Baby está hecho para manos cansadas a las 3 de la mañana.",
      steps: [
        { t: "Crea un perfil del bebé", d: "Nombre, fecha de nacimiento, foto opcional. Añade tantos bebés como necesite tu familia.", time: "~20 seg" },
        { t: "Registra el primer evento", d: "Una toma, un pañal, una siesta. Un toque en la pantalla principal y queda guardado.", time: "~5 seg" },
        { t: "Mira la línea del día", d: "Todo lo que has registrado, en orden, listo para compartir con tu pareja o pediatra.", time: "Instantáneo" },
      ],
      cta: "Útil en menos de un minuto. Y para siempre, después.",
    },
    feat: {
      eyebrow: "Funciones que importan",
      h2: "Un registro tranquilo de lo que de verdad pasa.",
      sub: "Pensado en torno a cinco pantallas que abrirás cada día — y otras que vas a guardar como un tesoro.",
      cards: [
        { tag: "Hitos · Recuerdos", t: "Sigue cada hito, organizado automáticamente.", d: "142 momentos del desarrollo, desde el nacimiento hasta los 60 meses. Toca cuando ocurra, adjunta una foto, escribe una frase. La app recuerda qué viene después.", pills: ["142 hitos", "0 → 60 meses", "Adjuntar fotos"], img: "assets/01-milestones.png" },
        { tag: "Checklists por edad", t: "No te pierdas ninguna etapa.", d: "Movimiento, visión y oído, social, lenguaje — desglosado por edad. Añade hitos personalizados para los que solo tu familia conoce.", pills: ["0–60 meses", "Personalizable"], img: "assets/02-checklist.png" },
        { tag: "Diario rápido", t: "Un toque. Registrado.", d: "Sueño, biberón, pecho, pis, caca, tiempo despierto, crecimiento, notas de salud. Marca lo que quieras recordarle al pediatra.", pills: ["Registro rápido", "Avisos al médico", "Temporizador"], img: "assets/03-diary.png" },
        { tag: "Línea del tiempo", t: "Una línea de tiempo para releer mil veces.", d: "Fotos, notas e hitos entretejidos en una historia visual a la que volverás siempre. Agrupado por mes y etapa.", pills: ["Recuerdos con fotos", "Agrupado solo"], img: "assets/04-journey.png" },
        { tag: "Tarjetas compartibles", t: "Tarjetas de progreso preciosas, con un toque.", d: "Envía una imagen con el último hito, crecimiento y un retrato adorable. Perfecto para el grupo familiar.", pills: ["Un toque", "Exportar imagen"], img: "assets/05-share.png" },
        { tag: "PDF para el pediatra", t: "Dale al médico un resumen claro.", d: "Exporta registros marcados, crecimiento e hitos recientes en un PDF de una página antes de la próxima visita. Nada sale del teléfono sin ti.", pills: ["Exportar PDF", "Pensado para médicos"] },
        { tag: "PDF Resumen del Año", t: "Un recuerdo al final de cada año.", d: "Un resumen imprimible de los hitos, fotos y crecimiento de los últimos 12 meses. Guárdalo, imprímelo, envíaselo a los abuelos.", pills: ["PDF anual", "Imprimible"] },
        { tag: "Copia & restauración", t: "Tus datos, en tus manos.", d: "Exporta un archivo de copia cuando quieras. Restaura en un teléfono nuevo con un toque. Sin cuenta, nunca.", pills: ["Copia local", "Restauración en un toque"] },
      ],
    },
    privacy: {
      eyebrow: "Privacidad por diseño",
      h2: "Los datos de tu bebé siguen siendo tuyos.",
      sub: "Sin cuentas que olvidar. Sin sincronizaciones en segundo plano. Sin redes publicitarias viendo crecer a tu hijo. Gamu Baby se construyó con una sola regla: nada sale del teléfono salvo que lo envíes tú.",
      items: [
        { t: "Guardado en tu dispositivo", d: "Registros, fotos y notas viven en el almacenamiento local del teléfono — en ningún otro sitio." },
        { t: "Sin cuenta", d: "Sin email, sin contraseña, sin registro. Abre la app y empieza." },
        { t: "Sin anuncios. Sin vender datos.", d: "No tenemos SDKs de publicidad ni analíticas que lean la información de tu hijo." },
        { t: "Tú decides cada exportación", d: "Las copias, PDFs y tarjetas solo salen del dispositivo cuando tú eliges enviarlas." },
      ],
      card: {
        badge: "Solo local",
        h: "Tu teléfono es el servidor.",
        d: "Gamu Baby funciona totalmente sin conexión. Vuelos, sótanos, noches confusas a las 3 de la mañana — sigue funcionando.",
        meta: [
          { k: "Cuentas", v: "0" },
          { k: "Rastreadores", v: "0" },
          { k: "SDKs de anuncios", v: "0" },
          { k: "Sync en la nube", v: "Apagado por defecto" },
        ],
        never: ["Nunca leemos tus registros.", "Nunca vendemos datos de bebés.", "Nunca pedimos iniciar sesión."],
      },
    },
    care: {
      eyebrow: "Invitar a cuidador",
      h2: "Comparte la app con quien te ayuda.",
      sub: "Pareja, abuelos, niñeras. Envía un código y podrán instalar Gamu Baby para llevar su propio registro — sin cuenta de grupo, sin nube compartida.",
      qrTitle: "Invitar a un cuidador",
      qrSub: "Escanea para instalar. Cada teléfono mantiene su propio registro privado.",
      qrBtnPrimary: "Compartir invitación",
      qrBtnSecondary: "Copiar código",
      disclaim: "Una invitación ayuda a otra persona a instalar la app. No expone tus registros automáticamente — compartir siempre es una decisión tuya, registro a registro.",
    },
    pro: {
      eyebrow: "Gamu Baby Pro",
      h2: "Una compra tranquila. Toda la app, para siempre.",
      sub: "Pro mantiene Gamu Baby sin anuncios, sin cuentas y hecho por humanos. Es un pago único, nunca una suscripción.",
      price: "",
      once: "",
      feat: [
        "Registros avanzados (crecimiento, avisos de salud, temporizador)",
        "Varios perfiles de bebé para mellizos y hermanos",
        "Tarjetas de hito compartibles",
        "Exportación de PDF para el pediatra",
        "PDF de Resumen del Año",
        "Copia & restauración",
      ],
      note: "La versión gratuita cubre los registros diarios y los hitos básicos — pruébala primero, mejora solo si te aporta.",
      cta: "Conseguir en Google Play",
    },
    final: {
      h2: "Empieza en privado. Hoy.",
      sub: "Abre la app y ya estás registrando. No hace falta cuenta.",
      primary: "Descargar en Google Play",
      reass: "Instalación gratis · Pro disponible dentro de la app",
    },
    foot: {
      tag: "Hecho por padres, para padres.",
      moreLabel: "Más apps de este desarrollador →",
      moreHref: "https://play.google.com/store/apps/dev?id=8831894198403002159",
      links: [],
      copy: "© 2026 Gamu Baby",
    },
  },

  ko: {
    nav: { features: "기능", privacy: "프라이버시", pro: "Pro", get: "Gamu Baby 받기" },
    hero: {
      eyebrow: "오프라인 우선 육아 기록",
      h1: "매일의 돌봄과 작은 성장의 순간을 위한, 조용한 기록.",
      sub: "수유, 기저귀, 수면, 성장, 사진, 추억 — 계정 없이, 클라우드 동기화 없이 기록하세요.",
      primary: "Google Play에서 받기",
      secondary: "어떻게 작동하는지 보기",
      trust: ["오프라인 지원", "계정 불필요", "광고 없음", "1회 결제 Pro"],
    },
    first: {
      eyebrow: "1분 안에 사용 가능",
      h2: "앱을 엽니다. 한 번 탭. 끝.",
      sub: "복잡한 온보딩도, 이메일도, 설정 마법사도 없어요. Gamu Baby는 새벽 3시의 지친 손을 위해 만들었습니다.",
      steps: [
        { t: "아기 프로필 만들기", d: "이름, 생일, 선택 사진. 가족이 필요한 만큼 아기를 추가할 수 있어요.", time: "약 20초" },
        { t: "첫 돌봄 기록 남기기", d: "수유, 기저귀, 낮잠. 홈 화면에서 한 번 탭하면 기록 완료.", time: "약 5초" },
        { t: "오늘의 타임라인 보기", d: "기록한 모든 것을 순서대로. 배우자나 소아과 선생님과 바로 공유 가능.", time: "즉시" },
      ],
      cta: "1분 안에 사용 가능. 그리고 그 이후로도 계속.",
    },
    feat: {
      eyebrow: "기능",
      h2: "실제로 일어나는 일들의 조용한 기록.",
      sub: "매일 열게 될 다섯 가지 화면과, 몇 년 뒤 소중히 다시 볼 화면들로 만들었습니다.",
      cards: [
        { tag: "마일스톤 · 추억", t: "모든 성장을 자동으로 정리.", d: "출생부터 60개월까지 142개의 발달 마일스톤. 일어났을 때 탭하고, 사진을 첨부하고, 한 줄을 남기세요. 다음 단계는 앱이 기억합니다.", pills: ["142개 마일스톤", "0 → 60개월", "사진 첨부"], img: "assets/01-milestones.png" },
        { tag: "연령별 체크리스트", t: "어떤 단계도 놓치지 않게.", d: "운동, 시각·청각, 사회성, 언어 — 월령별로 정리. 우리 가족만 아는 마일스톤도 직접 추가할 수 있어요.", pills: ["0–60개월", "사용자 정의"], img: "assets/02-checklist.png" },
        { tag: "빠른 기록 일지", t: "한 번 탭. 기록 완료.", d: "수면, 분유, 모유, 소변, 대변, 깨어 있는 시간, 성장, 건강 메모. 의사에게 보여줄 항목에 플래그를 달 수 있어요.", pills: ["빠른 기록", "진료용 플래그", "깨어 있는 타이머"], img: "assets/03-diary.png" },
        { tag: "여정 타임라인", t: "몇 번이고 다시 읽고 싶은 타임라인.", d: "사진, 메모, 마일스톤이 한 편의 이야기로 엮입니다. 월별과 단계별로 자동 정리.", pills: ["사진 추억", "자동 그룹핑"], img: "assets/04-journey.png" },
        { tag: "공유 카드", t: "한 번 탭으로 만드는 아름다운 성장 카드.", d: "최신 마일스톤, 성장 기록, 사랑스러운 사진 한 장. 가족 채팅방에 딱.", pills: ["원탭", "이미지 내보내기"], img: "assets/05-share.png" },
        { tag: "소아과 PDF", t: "선생님께 깔끔한 요약본을.", d: "플래그한 기록, 성장, 최근 마일스톤을 한 페이지 PDF로. 다음 진료 전에 준비 완료. 보내지 않는 한 데이터는 폰에서 나가지 않아요.", pills: ["PDF 내보내기", "진료용"] },
        { tag: "연간 리뷰 PDF", t: "한 해의 끝에 남기는 기념 한 권.", d: "지난 12개월의 마일스톤, 사진, 성장 기록을 인쇄 가능한 요약본으로. 저장하고, 인쇄하고, 조부모님께 보내드리세요.", pills: ["연간 PDF", "인쇄 가능"] },
        { tag: "백업 & 복원", t: "데이터는 당신의 손 안에.", d: "원할 때 백업 파일을 내보내고, 새 폰에서 한 번 탭으로 복원하세요. 계정은 필요 없습니다, 절대.", pills: ["로컬 백업", "원탭 복원"] },
      ],
    },
    privacy: {
      eyebrow: "설계부터 프라이빗",
      h2: "아기의 데이터는 당신의 것입니다.",
      sub: "잊어버릴 계정도, 백그라운드 동기화도, 아이의 성장을 지켜보는 광고 네트워크도 없습니다. Gamu Baby는 한 가지 규칙으로 만들어졌어요 — 당신이 보내지 않는 한, 폰을 떠나지 않습니다.",
      items: [
        { t: "기기에 저장", d: "기록, 사진, 메모는 모두 폰의 로컬 저장소에만 있어요." },
        { t: "계정 불필요", d: "이메일도, 비밀번호도, 가입도 없어요. 열면 바로 시작." },
        { t: "광고 없음. 데이터 판매 없음.", d: "광고 SDK도, 아이의 정보를 읽는 분석 도구도 들어있지 않습니다." },
        { t: "내보내기는 당신이 결정", d: "백업, PDF, 공유 카드는 당신이 보낼 때만 기기를 떠납니다." },
      ],
      card: {
        badge: "로컬 전용",
        h: "당신의 폰이 서버입니다.",
        d: "Gamu Baby는 완전히 오프라인으로 작동합니다. 비행기 안, 지하, 새벽 3시의 정신없는 시간에도 그대로 작동해요.",
        meta: [
          { k: "계정", v: "0" },
          { k: "트래커", v: "0" },
          { k: "광고 SDK", v: "0" },
          { k: "클라우드 동기화", v: "기본 꺼짐" },
        ],
        never: ["우리는 당신의 기록을 읽지 않습니다.", "우리는 아기 데이터를 팔지 않습니다.", "우리는 로그인을 요구하지 않습니다."],
      },
    },
    care: {
      eyebrow: "보호자 초대",
      h2: "도와주는 사람들과 앱을 공유하세요.",
      sub: "배우자, 조부모, 베이비시터. 코드를 보내면 그들도 자신의 폰에서 Gamu Baby를 시작할 수 있어요 — 공유 계정도, 공유 클라우드도 없습니다.",
      qrTitle: "보호자 초대하기",
      qrSub: "스캔해서 설치. 각 폰이 자신만의 비공개 기록을 유지합니다.",
      qrBtnPrimary: "초대 보내기",
      qrBtnSecondary: "코드 복사",
      disclaim: "초대는 상대가 앱을 설치하는 것을 돕는 것뿐입니다. 당신의 기록이 자동으로 공유되지는 않아요 — 공유는 언제나, 기록 하나하나에 대해, 당신의 선택입니다.",
    },
    pro: {
      eyebrow: "Gamu Baby Pro",
      h2: "한 번의 조용한 결제. 앱 전체를, 영원히.",
      sub: "Pro 덕분에 Gamu Baby는 광고 없이, 계정 없이, 사람의 손으로 만들어집니다. 구독이 아니라 1회 구매입니다.",
      price: "",
      once: "",
      feat: [
        "고급 일지 기록 (성장, 건강 플래그, 깨어 있는 타이머)",
        "쌍둥이·형제자매를 위한 여러 프로필",
        "공유 가능한 마일스톤 카드",
        "소아과용 PDF 내보내기",
        "연간 리뷰 PDF 기념본",
        "백업 & 복원",
      ],
      note: "무료 버전으로도 매일의 기록과 기본 마일스톤을 사용할 수 있어요. 먼저 써보고, 마음에 들면 Pro로.",
      cta: "Google Play에서 받기",
    },
    final: {
      h2: "오늘부터, 조용히 시작하세요.",
      sub: "앱을 여는 순간, 이미 기록은 시작되었습니다. 계정은 필요 없어요.",
      primary: "Google Play에서 받기",
      reass: "설치 무료 · Pro는 앱 내에서 1회 결제",
    },
    foot: {
      tag: "부모가, 부모를 위해 만들었습니다.",
      moreLabel: "이 개발자의 다른 앱 →",
      moreHref: "https://play.google.com/store/apps/dev?id=8831894198403002159",
      links: [],
      copy: "© 2026 Gamu Baby",
    },
  },
};

window.COPY = COPY;
