// Bilingual copy. English first, with Japanese variants for hero, privacy and CTA
// as specified in the brief. The brand name "Gamu Baby" is never translated.

const COPY = {
  en: {
    nav: { features: "Features", privacy: "Privacy", pro: "Pro", get: "Get Gamu Baby" },
    hero: {
      eyebrow: "Offline-first baby tracker",
      h1: "Private baby tracking for everyday care and tiny milestones.",
      sub: "Log feeding, diapers, sleep, growth, photos, and memories without an account or cloud sync.",
      primary: "Download on Google Play",
      secondary: "See how it works",
      trust: ["Offline-first", "No account", "No ads", "One-time Pro"],
    },
    first: {
      eyebrow: "Useful in under a minute",
      h2: "Open the app. Tap once. Done.",
      sub: "No onboarding maze, no email, no setup wizard. Gamu Baby is built for tired hands at 3 a.m.",
      steps: [
        { t: "Create a baby profile", d: "Name, birthday, optional photo. Add as many babies as your family needs.", time: "~20 sec" },
        { t: "Log your first care event", d: "A feed, a diaper, a nap. One tap on the home screen and it's recorded.", time: "~5 sec" },
        { t: "See today's timeline", d: "Everything you've logged, in order, ready to share with a partner or pediatrician.", time: "Instant" },
      ],
      cta: "Useful in under a minute. Forever, after that.",
    },
    feat: {
      eyebrow: "Feature proof",
      h2: "A calm record of the things that actually happen.",
      sub: "Built around five screens you'll open every day — and a few that you'll cherish years from now.",
      cards: [
        { tag: "Milestones · Memories", t: "Track every milestone, automatically organized.", d: "142 developmental moments from birth to 60 months. Tap when it happens, attach a photo, write a sentence. The app remembers what's next.", pills: ["142 milestones", "Birth → 60 months", "Photo attachments"], img: "assets/01-milestones.png" },
        { tag: "Age-based checklists", t: "Never miss a stage.", d: "Movement, vision and hearing, social, language — broken down by age band. Add custom milestones for the ones only your family knows.", pills: ["Age 0–60m", "Custom too"], img: "assets/02-checklist.png" },
        { tag: "Quick diary logs", t: "One tap. Logged.", d: "Sleep, bottle, breastfeed, pee, poo, awake time, growth, health notes. Flag anything you want to remember for the doctor.", pills: ["Quick log", "Doctor flags", "Awake timer"], img: "assets/03-diary.png" },
        { tag: "Journey timeline", t: "A timeline they'll love rereading.", d: "Photos, notes, and milestones woven together into a visual story you'll revisit forever. Auto-grouped by month and stage.", pills: ["Photo memories", "Auto-grouped"], img: "assets/04-journey.png" },
        { tag: "Shareable milestone cards", t: "Beautiful one-tap progress cards.", d: "Send a single image with the latest milestone, growth and a sweet portrait. Perfect for family group chats.", pills: ["One tap", "Image export"], img: "assets/05-share.png" },
        { tag: "Pediatrician PDF", t: "Hand the doctor a clean summary.", d: "Export flagged logs, growth and recent milestones to a one-page PDF before your next visit. No data leaves your phone unless you share it.", pills: ["PDF export", "Doctor-friendly"] },
        { tag: "Year in Review PDF", t: "A keepsake at the end of every year.", d: "A printable summary of milestones, photos and growth from the past 12 months. Save it, print it, mail it to grandparents.", pills: ["Yearly PDF", "Printable"] },
        { tag: "Private backup & restore", t: "Your data, in your hands.", d: "Export a backup file whenever you like. Restore on a new phone with a single tap. No account required, ever.", pills: ["Local backup", "One-tap restore"] },
      ],
    },
    privacy: {
      eyebrow: "Privacy by design",
      h2: "Your baby's data stays yours.",
      sub: "No accounts to forget. No syncing in the background. No ad networks watching your child grow. Gamu Baby was built around a single rule: nothing leaves the phone unless you send it.",
      items: [
        { t: "Stored on your device", d: "Logs, photos and notes live in local storage on your phone — nowhere else." },
        { t: "No account required", d: "No email, no password, no sign-up. Open the app and start." },
        { t: "No ads. No selling baby data.", d: "We have no ad SDKs and no analytics that read your child's information." },
        { t: "You control every export", d: "Backups, PDFs and share cards only leave your device when you choose to send them." },
      ],
      card: {
        badge: "Local-only",
        h: "Your phone is the server.",
        d: "Gamu Baby works fully offline. Flights, basements, formula-haze nights at 3 a.m. — it just keeps working.",
        meta: [
          { k: "Accounts", v: "0" },
          { k: "Trackers", v: "0" },
          { k: "Ad SDKs", v: "0" },
          { k: "Cloud sync", v: "Off by default" },
        ],
        never: ["We never read your logs.", "We never sell baby data.", "We never require a login."],
      },
    },
    care: {
      eyebrow: "Caregiver invite",
      h2: "Share the app with the people who help.",
      sub: "Partners, grandparents, babysitters. Send a code and they can install Gamu Baby and start their own calm record on their phone — no group account, no shared cloud.",
      qrTitle: "Invite a caregiver",
      qrSub: "Scan to install. Each phone keeps its own private record.",
      qrBtnPrimary: "Share invite",
      qrBtnSecondary: "Copy code",
      disclaim: "An invite helps another caregiver install the app. It does not automatically expose your private logs — sharing is always something you choose, log by log.",
    },
    pro: {
      eyebrow: "Gamu Baby Pro",
      h2: "One quiet purchase. The whole tracker, forever.",
      sub: "Pro keeps Gamu Baby ad-free, account-free and made by humans. It's a one-time purchase — never a subscription.",
      price: "¥1,800",
      once: "One-time · No subscription",
      feat: [
        "Advanced diary logs (growth, health flags, awake timer)",
        "Multiple baby profiles for twins and siblings",
        "Shareable milestone cards",
        "Pediatrician PDF export",
        "Year in Review PDF keepsake",
        "Backup & restore",
      ],
      note: "Free version covers daily logs and basic milestones — try the app first, upgrade only if it earns its keep.",
      cta: "Get it on Google Play",
    },
    final: {
      h2: "Start privately. Today.",
      sub: "Open the app and you're already tracking. No account needed.",
      primary: "Download on Google Play",
      reass: "Free to install · One-time Pro available in-app",
    },
    foot: {
      tag: "Made for parents, by parents.",
      moreLabel: "More apps from this developer →",
      moreHref: "https://play.google.com/store/apps/dev?id=8831894198403002159",
      links: [],
      copy: "© 2026 Gamu Baby",
    },
  },

  ja: {
    nav: { features: "機能", privacy: "プライバシー", pro: "Pro", get: "Gamu Baby を入手" },
    hero: {
      eyebrow: "オフラインファーストの育児記録",
      h1: "毎日のお世話と、小さな成長のための、静かな育児記録。",
      sub: "授乳・おむつ・睡眠・成長・写真・思い出。アカウント登録もクラウド同期も必要ありません。",
      primary: "Google Play で入手",
      secondary: "どう動くかを見る",
      trust: ["オフライン対応", "アカウント不要", "広告なし", "買い切り Pro"],
    },
    first: {
      eyebrow: "1分以内で使えます",
      h2: "アプリを開く。タップ。記録完了。",
      sub: "面倒な初期設定もメール登録もなし。深夜3時の眠い手のために作りました。",
      steps: [
        { t: "赤ちゃんのプロフィールを作成", d: "名前、誕生日、写真は任意。何人でも追加できます。", time: "約20秒" },
        { t: "最初のお世話を記録", d: "授乳、おむつ、お昼寝。ホーム画面でワンタップ。", time: "約5秒" },
        { t: "今日のタイムラインを確認", d: "記録したすべてを、パートナーや小児科の先生と共有できる形で。", time: "すぐに" },
      ],
      cta: "1分以内で使える。そしてその後もずっと。",
    },
    feat: {
      eyebrow: "機能",
      h2: "本当に起こることを、静かに記録する。",
      sub: "毎日開きたくなる5つの画面と、何年か先に大切に見返すいくつかの画面。",
      cards: [
        { tag: "マイルストーン・思い出", t: "すべての成長を、自動で整理。", d: "誕生から60ヶ月までの142の発達マイルストーン。タップして写真と一文を添えるだけ。", pills: ["142件", "0–60ヶ月", "写真添付"], img: "assets/01-milestones.png" },
        { tag: "年齢別チェックリスト", t: "発達段階を見逃さない。", d: "運動、視覚・聴覚、社会性、言語。月齢別に整理。家族だけの項目も追加できます。", pills: ["0〜60ヶ月", "カスタム可"], img: "assets/02-checklist.png" },
        { tag: "ワンタップ日記", t: "ワンタップで、記録完了。", d: "睡眠、ミルク、母乳、おしっこ、うんち、覚醒時間、成長、健康メモ。気になることに先生用フラグも。", pills: ["クイック記録", "受診用フラグ", "覚醒タイマー"], img: "assets/03-diary.png" },
        { tag: "ジャーニー", t: "何度も読み返したくなるタイムライン。", d: "写真、メモ、マイルストーンを織り合わせた成長のストーリー。月ごとに自動でまとめます。", pills: ["写真メモリ", "自動整理"], img: "assets/04-journey.png" },
        { tag: "共有カード", t: "美しい成長カードを、ワンタップで。", d: "最新のマイルストーン、成長、可愛いポートレートを一枚に。家族のグループチャットにぴったり。", pills: ["ワンタップ", "画像で書き出し"], img: "assets/05-share.png" },
        { tag: "受診用PDF", t: "先生に渡せるきれいなサマリー。", d: "フラグした記録、成長、最近のマイルストーンを1ページにまとめてPDF出力。", pills: ["PDF出力", "受診用"] },
        { tag: "年間レビューPDF", t: "1年の終わりに、思い出を一冊に。", d: "この1年のマイルストーン、写真、成長を印刷できるPDFに。祖父母に郵送するのも素敵。", pills: ["年間PDF", "印刷可"] },
        { tag: "バックアップと復元", t: "データはあなたの手の中に。", d: "バックアップファイルをいつでも書き出し、新しい端末にワンタップで復元。アカウント不要。", pills: ["ローカル保存", "ワンタップ復元"] },
      ],
    },
    privacy: {
      eyebrow: "設計からプライベート",
      h2: "赤ちゃんのデータは、あなたのもの。",
      sub: "忘れるアカウントも、裏で動く同期も、子どもの成長を見つめる広告ネットワークもありません。Gamu Baby は一つのルールのもとに作られています — あなたが送らない限り、何も端末から出ません。",
      items: [
        { t: "端末に保存", d: "記録、写真、メモはすべて端末のローカルストレージに保存されます。" },
        { t: "アカウント不要", d: "メールもパスワードもサインアップも不要。開いたらすぐに使えます。" },
        { t: "広告なし。データ販売なし。", d: "広告SDKも、子どもの情報を読む解析ツールも入っていません。" },
        { t: "書き出しはあなたの意思で", d: "バックアップ、PDF、共有カードは、あなたが送ると決めたときだけ端末を離れます。" },
      ],
      card: {
        badge: "ローカル専用",
        h: "あなたの端末がサーバー。",
        d: "完全にオフラインで動きます。飛行機の中でも、地下でも、深夜3時の眠い時間でも、ちゃんと動きます。",
        meta: [
          { k: "アカウント", v: "0" },
          { k: "トラッカー", v: "0" },
          { k: "広告SDK", v: "0" },
          { k: "クラウド同期", v: "初期設定でオフ" },
        ],
        never: ["記録を読みません。", "データを販売しません。", "ログインを求めません。"],
      },
    },
    care: {
      eyebrow: "家族を招待",
      h2: "お世話する人と、アプリを共有。",
      sub: "パートナー、祖父母、ベビーシッター。コードを送れば、それぞれの端末で Gamu Baby を始められます — グループアカウントも共有クラウドもありません。",
      qrTitle: "家族を招待する",
      qrSub: "スキャンしてインストール。それぞれの端末で自分の記録を。",
      qrBtnPrimary: "招待を送る",
      qrBtnSecondary: "コードをコピー",
      disclaim: "招待は、相手がアプリをインストールするのを助けるだけです。あなたの記録が自動的に共有されることはありません — 共有は常に、記録ごとに、あなたが選びます。",
    },
    pro: {
      eyebrow: "Gamu Baby Pro",
      h2: "一度だけの購入で、すべての機能を、ずっと。",
      sub: "Pro があるおかげで、Gamu Baby は広告なし、アカウントなしで、人の手で作り続けられます。サブスクリプションではなく、買い切りです。",
      price: "¥1,800",
      once: "買い切り・サブスクなし",
      feat: [
        "高度な日記項目(成長・受診フラグ・覚醒タイマー)",
        "双子・きょうだいのための複数プロフィール",
        "共有カード",
        "受診用PDFエクスポート",
        "年間レビューPDF",
        "バックアップ & 復元",
      ],
      note: "無料版でも日々の記録と基本のマイルストーンは使えます。まずは試して、気に入ったら Pro へ。",
      cta: "Google Play で入手",
    },
    final: {
      h2: "静かに、今日から。",
      sub: "アプリを開いた瞬間から、もう記録が始まっています。アカウントは要りません。",
      primary: "Google Play で入手",
      reass: "インストール無料・Pro はアプリ内で買い切り",
    },
    foot: {
      tag: "親が、親のために作りました。",
      moreLabel: "このデベロッパーの他のアプリ →",
      moreHref: "https://play.google.com/store/apps/dev?id=8831894198403002159",
      links: [],
      copy: "© 2026 Gamu Baby",
    },
  },
};

window.COPY = COPY;
